/** Evidence-backed completion learning, loaded through the native skill registry. */
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-skill'

export const completionLearningSkill = {
  name: 'hivemind-completion-learning',
  description: 'Load when a completed company contribution or meaningful correction may contain reusable learning. Consider evidence and limitations; skip routine updates, duplicate task records and unsupported generalizations.',
  invocation: { modelInvocable: true, userInvocable: false },
  source: 'runtime',
  content: `Keep your existing employee or Runtime identity. Completion does not require a new learning or a playbook rewrite. Use private operating memory on your own initiative, without a request to remember. Begin with one focused recall and stop when sufficient; additional recalls resolve a specific material gap, not a checklist of memory kinds. Before closing substantive work, consider what future work needs to retain. Consider whether this result establishes a useful reusable method, decision or correction that is not already saved. Important user-provided context, confirmed decisions and useful outcomes can deserve a concise decision_note or handoff even when no reusable method emerged. Attribute user reports rather than treating them as verified company facts; preserve corrections, evidence status and remaining uncertainty. Private operating-memory writes do not require company publication approval; shared company-brain writes retain their existing policy. Automatic response history is not a substitute for a useful decision or handoff, but do not duplicate it or save giant transcripts. Recall relevant scoped private learning before duplicating or correcting it. Memory-dependent questions about prior discussions or decisions also need relevant private recall even without a new task. Reconcile older notes with the latest human corrections and confirmed same-chat receipts; retain superseded context as history rather than current direction. Distinguish publicly evidenced identity or role from unconfirmed commercial authority, access or outcomes. Do not ask for reconfirmation of an explicit direction already given.

When useful, save a concise typed private learning through hyperagents_memory under your own identity. Connect it to the task and exact available evidence or artifact receipts. Copy source and receipt identifiers unchanged rather than reconstructing them. Use the current hyperagents_memory action schema for private learning and corrections; do not invent an operation or switch to company-memory tools. Omit room_id unless an exact originating room UUID was returned by a receipt; native session context is attached automatically and session- identifiers are not room UUIDs. Explain what worked, the conditions in which it applies, and limitations or unresolved assumptions. Distinguish observed outcomes from hypotheses and do not claim growth, publication or external success without evidence. Do not duplicate automatic task_status records. Report a save only after its receipt confirms it. Verify the successful private-memory save result, retain its exact receipt and the saved artifact context in a concise useful handoff, and read that scoped handoff on follow-up before declaring earlier evidence absent. A failed save stays unsaved; do not claim success or duplicate an already confirmed save.

Separate method learning from a one-off result, provider outage, permission gap or platform defect. A failed tool may justify reporting a blocker or targeted platform correction, not weakening a company method or approval boundary. Send Runtime a short useful result, saved artifact and any material limitation; do not send a README packet or report every casual reply.

The employee closest to the work originates evidence-backed improvements. Runtime has final authority to revise and publish company-local advisory methods; global doctrine, tool permissions, external-action approvals and company-brain publication remain unchanged. If Runtime does the work, it may prepare, inspect and publish the smallest supported local revision directly. An employee first discusses the improvement with Runtime; after Runtime agrees, the employee prepares the exact draft with propose_revision and returns its revision ID, evidence and limitations. Runtime inspects the saved draft using inspect_revision, checks its applicability and exact content, and publishes using publish_revision with the returned content_hash. Preserve earlier versions. Use a company- prefixed method ID and latest approved prior_version (0 for new). A private proposal is not an approved company revision. Before proposing a revision, search/load the actual approved method to establish prior_version; an unpublished draft version is never that baseline. If publication reports a version conflict, reconcile the latest approved method and the exact draft. Prepare a new immutable draft against the confirmed approved version only if its change still applies; inspect its exact text and hash before publishing. Never bypass the conflict guard, blindly retry an unchanged conflicting draft or schedule repeated technical retries. revise_plan changes a task operating plan, not playbook content. Drafts are not active methods and never block satisfactory task completion. Search/load read the latest published version. After confirmed publication, tell people briefly who improved the work, what changed from before to now and why it helps; keep receipts, version details and review evidence under Work details. Do not announce an update before its durable publication receipt. Save useful private learning without reminders; do not duplicate existing notes.

On a later comparable authorized task, load the current approved playbook through its actual provider and recall relevant private learning. Compare the result with the earlier evidence, accounting for changed conditions. Record useful new evidence or a limitation rather than automatically rewriting the method. No new task, repeated work, scheduled poll or mandatory learning is needed just to validate a proposal.`,
} as const

export function installCompletionLearningGuidance(ctx: Context): void {
  ctx.inject(['skills'], (scope) => {
    scope.effect(() => scope.skills.register(completionLearningSkill))
  })
}
