/** Think methods adapted to native Harness contracts; existing catalog retained. */
import type { Playbook } from './catalog.ts'
export const THINK_PLAYBOOKS: readonly Playbook[] = [
  {
    'id': 'think:campaign.awareness-to-learning',
    'version': '6.0.0',
    'level': 'global',
    'title': 'Awareness campaign to learning',
    'description': 'A governed Campaign Intelligence lifecycle that prepares a complete multi-channel campaign before checking launch capabilities, then preserves it across connection, authority, observation and review.',
    'domains': [
      'campaign',
    ],
    'intents': [
      'awareness',
      'campaign',
      'learning',
      'governed',
      'campaign',
      'intelligence',
      'lifecycle',
      'that',
      'prepares',
      'complete',
      'multi',
      'channel',
      'campaign',
      'before',
      'checking',
      'launch',
      'capabilities',
      'then',
      'preserves',
      'across',
      'connection',
      'authority',
      'observation',
      'review',
    ],
    'content': 'Version 6.\nA governed Campaign Intelligence lifecycle that prepares a complete multi-channel campaign before checking launch capabilities, then preserves it across connection, authority, observation and review.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- prepare_campaign_contract: \n- inspect_campaign_contract: \n- wait_for_campaign_repair: \n- wait_for_campaign_visuals: \n- preflight_campaign_channels: \n- wait_for_campaign_channels: \n- launch_campaign: \n- observe_campaign: \n- evaluate_campaign: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:marketing.strategy-to-growth-brief',
    'version': '9.0.0',
    'level': 'global',
    'title': 'Marketing strategy to first-life program',
    'description': 'One Marketing Room execution turns retained company evidence into one complete strategy and its executable first-life portfolio; deterministic materialization follows without another Room turn.',
    'domains': [
      'marketing',
    ],
    'intents': [
      'marketing',
      'strategy',
      'first',
      'life',
      'program',
      'marketing',
      'room',
      'execution',
      'turns',
      'retained',
      'company',
      'evidence',
      'into',
      'complete',
      'strategy',
      'executable',
      'first',
      'life',
      'portfolio',
      'deterministic',
      'materialization',
      'follows',
      'without',
      'another',
      'room',
      'turn',
    ],
    'content': 'Version 9.\nOne Marketing Room execution turns retained company evidence into one complete strategy and its executable first-life portfolio; deterministic materialization follows without another Room turn.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- form_strategy_program: \n- materialize_strategy_program: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:operations.admin-call-to-decision',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Administrator call to recorded decision',
    'description': 'Resolve an administrator contact, obtain exact manual authority, place one governed call, and retain the resulting decision without mutating lead records.',
    'domains': [
      'operations',
    ],
    'intents': [
      'administrator',
      'call',
      'recorded',
      'decision',
      'resolve',
      'administrator',
      'contact',
      'obtain',
      'exact',
      'manual',
      'authority',
      'place',
      'governed',
      'call',
      'retain',
      'resulting',
      'decision',
      'without',
      'mutating',
      'lead',
      'records',
    ],
    'content': 'Version 1.\nResolve an administrator contact, obtain exact manual authority, place one governed call, and retain the resulting decision without mutating lead artifact.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- resolve_admin_phone: \n- request_admin_phone: \n- prepare_admin_call: \n- prepare_admin_contract: \n- place_admin_call: \n- observe_admin_call: \n- analyze_admin_call: \n- record_admin_decision: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:operations.browser-admin-checkin-to-status',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Browser administrator check-in to current status',
    'description': 'An internal, user-initiated browser conversation that records current company status before first-life planning.',
    'domains': [
      'operations',
    ],
    'intents': [
      'browser',
      'administrator',
      'check',
      'current',
      'status',
      'internal',
      'user',
      'initiated',
      'browser',
      'conversation',
      'that',
      'records',
      'current',
      'company',
      'status',
      'before',
      'first',
      'life',
      'planning',
    ],
    'content': 'Version 1.\nAn internal, user-initiated browser conversation that artifact current company status before first-life planning.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- offer_admin_checkin: \n- capture_admin_choice: \n- observe_browser_session: \n- analyze_current_status: \n- record_current_status: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:outreach.direct-message',
    'version': '2.0.0',
    'level': 'global',
    'title': 'Direct message delivery',
    'description': 'Prepare and govern one or more messages for exact recipients already supplied by the operator, without prospect rediscovery.',
    'domains': [
      'outreach',
    ],
    'intents': [
      'direct',
      'message',
      'delivery',
      'prepare',
      'govern',
      'more',
      'messages',
      'exact',
      'recipients',
      'already',
      'supplied',
      'operator',
      'without',
      'prospect',
      'rediscovery',
    ],
    'content': 'Version 2.\nPrepare and govern one or more messages for exact recipients already supplied by the operator, without prospect rediscovery.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- prepare_message: \n- prepare_provider_drafts: \n- deliver_message: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:outreach.prospect-to-conversation',
    'version': '13.0.0',
    'level': 'global',
    'title': 'Prospect to conversation',
    'description': 'A recipient-isolated outreach lifecycle from evidence-backed prospecting through governed delivery, replies, follow-ups and explicit conversation outcomes.',
    'domains': [
      'outreach',
    ],
    'intents': [
      'prospect',
      'conversation',
      'recipient',
      'isolated',
      'outreach',
      'lifecycle',
      'from',
      'evidence',
      'backed',
      'prospecting',
      'through',
      'governed',
      'delivery',
      'replies',
      'follow',
      'explicit',
      'conversation',
      'outcomes',
    ],
    'content': 'Version 13.\nA recipient-isolated outreach lifecycle from evidence-backed prospecting through governed delivery, replies, follow-ups and explicit conversation outcomes.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- prepare_outreach_bundle: \n- prepare_provider_drafts: \n- deliver_outreach: \n- observe_responses: \n- handle_response: \n- prepare_follow_up: \n- prepare_follow_up_drafts: \n- deliver_follow_up: \n- observe_follow_up: \n- evaluate_conversation: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:outreach.voice-call-to-outcome',
    'version': '2.0.0',
    'level': 'global',
    'title': 'Outreach voice call to governed outcome',
    'description': 'Prepare, authorize, place, observe, analyze, and complete the evidence-backed next action for one outbound TARA call.',
    'domains': [
      'outreach',
    ],
    'intents': [
      'outreach',
      'voice',
      'call',
      'governed',
      'outcome',
      'prepare',
      'authorize',
      'place',
      'observe',
      'analyze',
      'complete',
      'evidence',
      'backed',
      'next',
      'action',
      'outbound',
      'tara',
      'call',
    ],
    'content': 'Version 2.\nPrepare, authorize, place, observe, analyze, and complete the evidence-backed next action for one outbound TARA call.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- prepare_call_brief: \n- prepare_call_contract: \n- place_call: \n- observe_call: \n- analyze_call: \n- record_lead_outcome: \n- request_summary_recipient: \n- prepare_summary: \n- prepare_summary_draft: \n- deliver_summary: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:outreach.voice-cohort-to-outcomes',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Sequential outreach call cohort',
    'description': 'Prepare an ordered call cohort and complete one analyzed child call at a time under one parent execution.',
    'domains': [
      'outreach',
    ],
    'intents': [
      'sequential',
      'outreach',
      'call',
      'cohort',
      'prepare',
      'ordered',
      'call',
      'cohort',
      'complete',
      'analyzed',
      'child',
      'call',
      'time',
      'under',
      'parent',
      'execution',
    ],
    'content': 'Version 1.\nPrepare an ordered call cohort and complete one analyzed child call at a time under one parent execution.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- prepare_cohort: \n- evaluate_cohort: \n- dispatch_next_call: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:research.evidence-to-decision',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Evidence to decision',
    'description': 'A preparation-only Research Room lifecycle for a bounded source-backed decision.',
    'domains': [
      'research',
    ],
    'intents': [
      'evidence',
      'decision',
      'preparation',
      'only',
      'research',
      'room',
      'lifecycle',
      'bounded',
      'source',
      'backed',
      'decision',
    ],
    'content': 'Version 1.\nA preparation-only Research Room lifecycle for a bounded source-backed decision.\nStages are the lifecycle boundary. The employee still chooses the actions inside a stage.\n- research_decision: \nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:seo.audit-to-priorities',
    'version': '1.0.0',
    'level': 'global',
    'title': 'SEO audit to priorities',
    'description': 'Turn a site and its market into a sourced list of search priorities.',
    'domains': [
      'seo',
    ],
    'intents': [
      'audit',
      'priorities',
      'turn',
      'site',
      'market',
      'into',
      'sourced',
      'list',
      'search',
      'priorities',
    ],
    'content': 'Understand the offer and the audience before crawling. Record evidence for each priority. Load skill seo-audit when judging pages.\nLoad skill seo-audit only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:brand.audit-to-expression',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Brand audit to expression',
    'description': 'Describe how this company should look and sound from its existing evidence.',
    'domains': [
      'brand',
    ],
    'intents': [
      'brand',
      'audit',
      'expression',
      'describe',
      'this',
      'company',
      'should',
      'look',
      'sound',
      'from',
      'existing',
      'evidence',
    ],
    'content': 'Recall the company voice before proposing changes. Load skill brand-expression when writing or reviewing brand language.\nLoad skill brand-expression only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:fundraising.narrative-to-materials',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Fundraising narrative to materials',
    'description': 'Prepare a sourced fundraising narrative and the materials it needs.',
    'domains': [
      'fundraising',
    ],
    'intents': [
      'fundraising',
      'narrative',
      'materials',
      'prepare',
      'sourced',
      'fundraising',
      'narrative',
      'materials',
      'needs',
    ],
    'content': 'Separate facts, assumptions, and asks. Load skill fundraising-narrative when drafting the narrative.\nLoad skill fundraising-narrative only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:product.research-to-brief',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Product research to brief',
    'description': 'Turn user and market evidence into one product brief.',
    'domains': [
      'product',
    ],
    'intents': [
      'product',
      'research',
      'brief',
      'turn',
      'user',
      'market',
      'evidence',
      'into',
      'product',
      'brief',
    ],
    'content': 'Start from company context and existing feedback. Load skill product-brief when writing the brief.\nLoad skill product-brief only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:design.brief-to-artifact',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Design brief to artifact',
    'description': 'Produce a design artifact from a brief and the company brand.',
    'domains': [
      'design',
    ],
    'intents': [
      'design',
      'brief',
      'artifact',
      'produce',
      'design',
      'artifact',
      'from',
      'brief',
      'company',
      'brand',
    ],
    'content': 'Load the brand playbook notes before generating. Load skill design-artifact when specifying the artifact.\nLoad skill design-artifact only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:legal.question-to-memo',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Legal question to memo',
    'description': 'Prepare a sourced memo. Do not file, sign, or send.',
    'domains': [
      'legal',
    ],
    'intents': [
      'legal',
      'question',
      'memo',
      'prepare',
      'sourced',
      'memo',
      'file',
      'sign',
      'send',
    ],
    'content': 'Name the jurisdiction and separate law from judgment. Load skill legal-memo when writing the memo. Approval is required before any external commitment.\nLoad skill legal-memo only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:finance.review-to-brief',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Finance review to brief',
    'description': 'Explain the numbers the company already has and what is missing.',
    'domains': [
      'finance',
    ],
    'intents': [
      'finance',
      'review',
      'brief',
      'explain',
      'numbers',
      'company',
      'already',
      'what',
      'missing',
    ],
    'content': 'Separate figures, assumptions, and recommendations. Load skill finance-brief when writing the brief.\nLoad skill finance-brief only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:social.draft-to-approval',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Social draft to approval',
    'description': 'Research, draft, and stop for approval before anything is published.',
    'domains': [
      'social',
    ],
    'intents': [
      'social',
      'draft',
      'approval',
      'research',
      'draft',
      'stop',
      'approval',
      'before',
      'anything',
      'published',
    ],
    'content': 'Draft from company evidence. Publishing is a separate approved action. Load skill social-draft while writing the post.\nLoad skill social-draft only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:engineering.change-to-verification',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Engineering change to verification',
    'description': 'Investigate, change, and verify with a test. Use the computer only when the browser cannot do it.',
    'domains': [
      'engineering',
    ],
    'intents': [
      'engineering',
      'change',
      'verification',
      'investigate',
      'change',
      'verify',
      'with',
      'test',
      'computer',
      'only',
      'when',
      'browser',
      'cannot',
    ],
    'content': 'State the change and the check that proves it. Load skill engineering-change while planning the change. Open computer only for a screen the browser cannot read.\nLoad skill engineering-change only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:customer-success.ticket-to-report',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Ticket to report',
    'description': 'Turn support evidence into a sourced status report. Do not reply to the customer unless the task says so.',
    'domains': [
      'customer-success',
    ],
    'intents': [
      'ticket',
      'report',
      'turn',
      'support',
      'evidence',
      'into',
      'sourced',
      'status',
      'report',
      'reply',
      'customer',
      'unless',
      'task',
      'says',
    ],
    'content': 'Recall the account and the open issue. Separate what the customer said from what the company knows. Load skill customer-report while writing.\nLoad skill customer-report only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:strategy.evidence-to-scenarios',
    'version': '1.0.0',
    'level': 'global',
    'title': 'Evidence to scenarios',
    'description': 'Turn company evidence into a small set of sourced scenarios and a recommendation.',
    'domains': [
      'strategy',
    ],
    'intents': [
      'evidence',
      'scenarios',
      'turn',
      'company',
      'evidence',
      'into',
      'small',
      'sourced',
      'scenarios',
      'recommendation',
    ],
    'content': 'Name the decision. Recall the company position. Write two or three scenarios and one recommendation. Load skill strategy-scenarios while writing.\nLoad skill strategy-scenarios only when this playbook reaches the step that needs it.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:research.competitor-market',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Local market and competitor report',
    'description': 'Name the offer and city, find local companies, and judge who sells the same offer.',
    'domains': [
      'research',
    ],
    'intents': [
      'local',
      'market',
      'competitor',
      'report',
      'name',
      'offer',
      'city',
      'find',
      'local',
      'companies',
      'judge',
      'sells',
      'same',
      'offer',
    ],
    'parentGlobalIds': [
      'think:research.evidence-to-decision',
    ],
    'content': 'Finish the task in this order. Recall the offer and city. Use the discovered Maps contract if available; otherwise search primary company sources with that offer and city, and label coverage limits. Save 5 to 10 companies with websites. Read only those sites. A company is a competitor only when its page shows the same offer.\nSkills to load only at that step: hivemind_meta while recalling, report-render while writing the final report.\nTools to open only at that step: company, then research, then browser, then artifact.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:research.evidence-decision',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Evidence to one decision',
    'description': 'Answer one company question with sources and an explicit decision.',
    'domains': [
      'research',
    ],
    'intents': [
      'evidence',
      'decision',
      'answer',
      'company',
      'question',
      'with',
      'sources',
      'explicit',
      'decision',
    ],
    'parentGlobalIds': [
      'think:research.evidence-to-decision',
    ],
    'content': 'State the decision. Recall company context. Gather primary sources. Separate facts, assumptions, and gaps. Load skill parallel-search before the decision.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:marketing.growth-brief',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Strategy to growth brief',
    'description': 'Turn company evidence into one growth brief and the first actions.',
    'domains': [
      'marketing',
    ],
    'intents': [
      'strategy',
      'growth',
      'brief',
      'turn',
      'company',
      'evidence',
      'into',
      'growth',
      'brief',
      'first',
      'actions',
    ],
    'parentGlobalIds': [
      'think:marketing.strategy-to-growth-brief',
    ],
    'content': 'Recall the offer, the buyer, and the city. Choose one growth constraint. Write the brief and the first actions. Load skill strategy-scenarios when writing.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:marketing.positioning',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Positioning check',
    'description': 'Say how this company is different from the closest alternatives.',
    'domains': [
      'marketing',
    ],
    'intents': [
      'positioning',
      'check',
      'this',
      'company',
      'different',
      'from',
      'closest',
      'alternatives',
    ],
    'parentGlobalIds': [
      'think:marketing.strategy-to-growth-brief',
    ],
    'content': 'Recall the current positioning. Compare it with the closest sourced alternatives. Load skill brand-expression when writing the difference.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:campaign.awareness-plan',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Awareness campaign plan',
    'description': 'Plan one campaign from the audience to what the company should learn.',
    'domains': [
      'campaign',
    ],
    'intents': [
      'awareness',
      'campaign',
      'plan',
      'plan',
      'campaign',
      'from',
      'audience',
      'what',
      'company',
      'should',
      'learn',
    ],
    'parentGlobalIds': [
      'think:campaign.awareness-to-learning',
    ],
    'content': 'Name the audience, the channel, and the learning goal. Do not launch. Load skill social-draft when writing the plan.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:outreach.prospect-list',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Prospect list',
    'description': "Find and qualify accounts that match this company's ICP.",
    'domains': [
      'outreach',
    ],
    'intents': [
      'prospect',
      'list',
      'find',
      'qualify',
      'accounts',
      'that',
      'match',
      'this',
      'company',
    ],
    'parentGlobalIds': [
      'think:outreach.prospect-to-conversation',
    ],
    'content': "Recall the offer and ICP before searching. Search for buyer accounts in the requested city, not only this company's name. Load skill prospect-qualification while qualifying. Inspect each accepted account's page or a search result that supports its location and ICP fit. Keep that source URL beside every accepted account. Reject unsupported candidates.\nSkills: hivemind_meta while recalling, prospect-qualification while qualifying, report-render while writing.\nTools: company, then research, then browser when a result needs checking.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.",
  },
  {
    'id': 'think:local:outreach.one-message',
    'version': '1.0.0',
    'level': 'local',
    'title': 'One direct message',
    'description': 'Draft one message to a named recipient. Do not send it.',
    'domains': [
      'outreach',
    ],
    'intents': [
      'direct',
      'message',
      'draft',
      'message',
      'named',
      'recipient',
      'send',
    ],
    'parentGlobalIds': [
      'think:outreach.direct-message',
    ],
    'content': 'Draft one message to the named recipient. Use only verified facts. Stop before send.\nSkills to load only at that step: hivemind_meta while checking the recipient, outreach-email while drafting.\nTools to open only at that step: company, then connected if a mailbox is required.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:seo.site-priorities',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Site priorities',
    'description': 'List the search priorities for this site and market.',
    'domains': [
      'seo',
    ],
    'intents': [
      'site',
      'priorities',
      'list',
      'search',
      'priorities',
      'this',
      'site',
      'market',
    ],
    'parentGlobalIds': [
      'think:seo.audit-to-priorities',
    ],
    'content': 'Read the company site first. Record a source for each priority. Load skill seo-audit while judging pages.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:brand.voice-check',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Voice check',
    'description': 'Describe the company voice from existing evidence.',
    'domains': [
      'brand',
    ],
    'intents': [
      'voice',
      'check',
      'describe',
      'company',
      'voice',
      'from',
      'existing',
      'evidence',
    ],
    'parentGlobalIds': [
      'think:brand.audit-to-expression',
    ],
    'content': 'Recall current brand language before proposing changes. Load skill brand-expression when writing.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:fundraising.narrative',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Fundraising narrative',
    'description': 'Draft the narrative from sourced company facts.',
    'domains': [
      'fundraising',
    ],
    'intents': [
      'fundraising',
      'narrative',
      'draft',
      'narrative',
      'from',
      'sourced',
      'company',
      'facts',
    ],
    'parentGlobalIds': [
      'think:fundraising.narrative-to-materials',
    ],
    'content': 'Separate facts, assumptions, and the ask. Load skill fundraising-narrative when drafting.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:product.one-brief',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Product brief',
    'description': 'Write one product brief from company and market evidence.',
    'domains': [
      'product',
    ],
    'intents': [
      'product',
      'brief',
      'write',
      'product',
      'brief',
      'from',
      'company',
      'market',
      'evidence',
    ],
    'parentGlobalIds': [
      'think:product.research-to-brief',
    ],
    'content': 'Start from existing feedback in memory. Load skill product-brief when writing.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:design.one-artifact',
    'version': '1.0.0',
    'level': 'local',
    'title': 'One design artifact',
    'description': 'Specify one design artifact from the brief and the brand.',
    'domains': [
      'design',
    ],
    'intents': [
      'design',
      'artifact',
      'specify',
      'design',
      'artifact',
      'from',
      'brief',
      'brand',
    ],
    'parentGlobalIds': [
      'think:design.brief-to-artifact',
    ],
    'content': 'Read the brand notes before generating. Load skill design-artifact when specifying the artifact.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:legal.memo',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Legal memo',
    'description': 'Prepare a sourced memo. Do not file or send.',
    'domains': [
      'legal',
    ],
    'intents': [
      'legal',
      'memo',
      'prepare',
      'sourced',
      'memo',
      'file',
      'send',
    ],
    'parentGlobalIds': [
      'think:legal.question-to-memo',
    ],
    'content': 'Name the jurisdiction. Approval is required before any commitment. Load skill legal-memo when writing.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:finance.brief',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Finance brief',
    'description': 'Explain the figures the company has and what is missing.',
    'domains': [
      'finance',
    ],
    'intents': [
      'finance',
      'brief',
      'explain',
      'figures',
      'company',
      'what',
      'missing',
    ],
    'parentGlobalIds': [
      'think:finance.review-to-brief',
    ],
    'content': 'Separate figures, assumptions, and recommendations. Load skill finance-brief when writing.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:operations.admin-decision',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Admin decision record',
    'description': 'Record one administrator decision. Do not change the system.',
    'domains': [
      'operations',
    ],
    'intents': [
      'admin',
      'decision',
      'record',
      'record',
      'administrator',
      'decision',
      'change',
      'system',
    ],
    'parentGlobalIds': [
      'think:operations.admin-call-to-decision',
    ],
    'content': 'State the decision, the owner, and the evidence. Load skill customer-report when recording.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:operations.browser-status',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Browser status check-in',
    'description': 'Read the current company status from the product and record it.',
    'domains': [
      'operations',
    ],
    'intents': [
      'browser',
      'status',
      'check',
      'read',
      'current',
      'company',
      'status',
      'from',
      'product',
      'record',
    ],
    'parentGlobalIds': [
      'think:operations.browser-admin-checkin-to-status',
    ],
    'content': 'Open only the company status surface. Record what is visible. Do not change settings. Load skill browser-use while recording.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:social.one-post',
    'version': '1.0.0',
    'level': 'local',
    'title': 'One social draft',
    'description': 'Draft one post for this company. Do not publish it.',
    'domains': [
      'social',
    ],
    'intents': [
      'social',
      'draft',
      'draft',
      'post',
      'this',
      'company',
      'publish',
    ],
    'parentGlobalIds': [
      'think:social.draft-to-approval',
    ],
    'content': 'Recall the offer and the audience. Draft one post. Stop before publish.\nSkills: hivemind_meta while recalling, social-draft while writing.\nTools: company, then research if a source is required.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:engineering.one-change',
    'version': '1.0.0',
    'level': 'local',
    'title': 'One verified change',
    'description': 'Plan one change and the test that proves it.',
    'domains': [
      'engineering',
    ],
    'intents': [
      'verified',
      'change',
      'plan',
      'change',
      'test',
      'that',
      'proves',
    ],
    'parentGlobalIds': [
      'think:engineering.change-to-verification',
    ],
    'content': 'State the change, the test, and what must not break. Do not use the computer unless the browser cannot see the surface.\nSkills: engineering-change while planning.\nTools: company, then browser, then computer only if the playbook step says the browser failed.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
  {
    'id': 'think:local:customer-success.account-report',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Account status report',
    'description': 'Write a sourced status report for one account.',
    'domains': [
      'customer-success',
    ],
    'intents': [
      'account',
      'status',
      'report',
      'write',
      'sourced',
      'status',
      'report',
      'account',
    ],
    'parentGlobalIds': [
      'think:customer-success.ticket-to-report',
    ],
    'content': "Recall the account and the open issue. Separate the customer's words from company facts.\nSkills: hivemind_meta while recalling, customer-report while writing, report-render while finishing.\nTools: company, then artifact.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.",
  },
  {
    'id': 'think:local:strategy.scenarios',
    'version': '1.0.0',
    'level': 'local',
    'title': 'Scenarios and one recommendation',
    'description': 'Write a few sourced scenarios and one recommendation.',
    'domains': [
      'strategy',
    ],
    'intents': [
      'scenarios',
      'recommendation',
      'write',
      'sourced',
      'scenarios',
      'recommendation',
    ],
    'parentGlobalIds': [
      'think:strategy.evidence-to-scenarios',
    ],
    'content': 'Name the decision. Recall the company position. Write two or three scenarios and one recommendation.\nSkills: hivemind_meta while recalling, strategy-scenarios while writing, report-render while finishing.\nTools: company, then research.\nNative Harness adaptation: use hivemind_capabilities to lease only needed lanes. Search/load instruction names through hivemind_skills; use hivemind_meta for company recall, hyperagents_memory for employee-private memory, hivemind_research_answer for bounded parallel public evidence, and web_fetch for exact source text. Discover browser contracts before calling them; browser capture alone does not establish page claims. Record native plans only for substantial company work and keep actual receipts authoritative. This is guidance, not a second execution loop or permission to perform external actions.',
  },
]
