/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository — the event
 * vocabulary this build understands. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`): such a log was likely written by a newer harness, and
 * silently skipping a required event would reconstruct a wrong session.
 * Downstream (out-of-repo) plugin events are outside this list by
 * construction. The persisted `SessionEvent.ignorable` marker is the
 * compatibility mechanism; event-name registration was rejected because
 * it does not classify omission safety and would make reads
 * composition-dependent. The rationale is in
 * `.agents/notes/implemented/architecture/2026-08-30-retain-ignorable-external-session-events.md`.
 */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/attempt',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'deliverables/presented',
  'feedback/message-delete',
  'feedback/message-put',
  'feedback/record',
  'goal/change',
  'hivemind/artifact-created',
  'hivemind/browser-capability-lease',
  'hivemind/browser-capture',
  'hivemind/capability-lease',
  'hivemind/composio-session',
  'hivemind/connected-receipt',
  'hivemind/decision',
  'hivemind/dream-source',
  'hivemind/employee-delegation-end',
  'hivemind/employee-delegation-start',
  'hivemind/employee-selection',
  'hivemind/evidence-gap-recorded',
  'hivemind/generation-created',
  'hivemind/media-workflow-ended',
  'hivemind/media-workflow-started',
  'hivemind/memory-save',
  'hivemind/operating-context',
  'hivemind/operating-receipt',
  'hivemind/playbooks-loaded',
  'hivemind/read-scope',
  'hivemind/reply-language',
  'hivemind/request-assembly-budget',
  'hivemind/research-gathered',
  'hivemind/research-receipt',
  'hivemind/research-requested',
  'hivemind/research-workflow-started',
  'hivemind/research-workflow-terminal',
  'hivemind/run-evaluation',
  'hivemind/run-plan',
  'hivemind/run-plan-revised',
  'hivemind/session-owner',
  'hivemind/task-memory-pending',
  'hivemind/task-memory-recorded',
  'hivemind/workstream-approval',
  'hivemind/workstream-completed',
  'hivemind/workstream-failed',
  'hivemind/workstream-progress',
  'hivemind/workstream-started',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'model/selection',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session-log-deepseek/delivery-accepted',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/catalog',
  'subagent/descriptor',
  'subagent/model-selection-policy',
  'system/message',
  'team/member',
  'team/message/delivered',
  'team/message/queued',
  'team/task',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/ptc-dispatch',
  'tool/ptc-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
])
