/** Localized first-entry Runtime presentation; work starts only on explicit wake. */
export const tourEn = {
  'tour.0.eyebrow': 'Your company, with a chief of staff',
  'tour.0.title': 'Meet Runtime.',
  'tour.0.text': 'A thoughtful partner for your company. Runtime keeps the big picture in view and helps turn your priorities into progress.',
  'tour.1.eyebrow': 'Start with what matters',
  'tour.1.title': 'Your context. Your direction.',
  'tour.1.text': 'Share what your company is building and the goals that matter next. Runtime learns from the company knowledge and connected apps you allow.',
  'tour.2.eyebrow': 'A team around you',
  'tour.2.title': 'Specialists, working together.',
  'tour.2.text': 'Your HyperAgents bring different strengths. Runtime coordinates their work, follows their progress, and brings their findings back to this room.',
  'tour.3.eyebrow': 'You stay in control',
  'tour.3.title': 'Clear results. Thoughtful decisions.',
  'tour.3.text': 'Review discoveries and finished work here. Runtime asks when your judgment or permission is needed, and you can pause company activity at any time.',
  'tour.4.eyebrow': 'One room to begin',
  'tour.4.title': 'Ready when you are.',
  'tour.4.text': 'Wake Runtime to explore your company and introduce your team. Opening this room or finishing this tour won’t start work.',
  'tour.conflict': 'Your tour changed in another tab. Continue from the saved step.',
  'tour.saveFailed': 'Your place couldn’t be saved. Please try again.',
  'tour.wakeFailed': 'Awakening couldn’t be confirmed. Try again to check this same request.',
  'tour.loadFailed': 'Runtime’s status couldn’t be checked. Please try again.',
  'tour.loading': 'Getting your welcome ready…',
  'tour.sleeping': 'Your chief of staff is ready to meet you.',
  'tour.accepted': 'Your wake request is saved. Waiting for Runtime to begin.',
  'tour.blocked': 'Runtime needs your help to finish awakening. Continue in this room.',
  'tour.exploring': 'Runtime is getting to know your company. Follow its progress in this room.',
  'tour.unfinished': 'Awakening is unfinished. Continue with Runtime in this room.',
  'tour.label': 'Meet Runtime',
  'tour.walkthrough': 'Runtime walkthrough',
  'tour.alt': 'Runtime, your retro computer chief of staff',
  'tour.step': 'Step {current} of 5',
  'tour.back': 'Back',
  'tour.later': 'Later',
  'tour.next': 'Next',
  'tour.finish': 'Finish tour',
  'tour.wake': 'Wake me up',
  'tour.checking': 'Checking…',
  'tour.view': 'View tour',
  'tour.continue': 'Continue tour',
  'tour.check': 'Check progress',
  'tour.resume': 'Continue awakening',
  'tour.bringAlive': 'Bring Runtime to life.',
  'tour.awakening': 'Runtime is awakening.',
  'tour.refreshFailed': 'Runtime’s status couldn’t be refreshed.',
  'tour.retry': 'Try again',
} as const
/** Keys registered in the native HIVEMIND HQ locale namespace. */
export type TourKey = keyof typeof tourEn
/** Chinese first-entry presentation, with the same human-action semantics. */
export const tourZh: Record<TourKey, string> = {
  'tour.0.eyebrow': '公司的智能参谋',
  'tour.0.title': '认识 Runtime。',
  'tour.0.text': 'Runtime 是您公司的贴心伙伴，关注全局，帮助您推动重要事项。',
  'tour.1.eyebrow': '从重要事项开始',
  'tour.1.title': '您的背景，您的方向。',
  'tour.1.text': '分享公司正在建设的事业和下一步目标。Runtime 通过您允许的公司知识和已连接应用了解情况。',
  'tour.2.eyebrow': '您的协作团队',
  'tour.2.title': '各有所长，携手协作。',
  'tour.2.text': 'HyperAgents 各有所长。Runtime 协调工作、关注进展，并将发现带回这个房间。',
  'tour.3.eyebrow': '您始终掌握方向',
  'tour.3.title': '清晰的成果，周全的决策。',
  'tour.3.text': '在此查看发现与成果。需要您的判断或许可时，Runtime 会询问您。您可随时暂停公司活动。',
  'tour.4.eyebrow': '从这个房间开始',
  'tour.4.title': '准备好时，就开始。',
  'tour.4.text': '唤醒 Runtime，让它了解公司并介绍团队。打开房间或完成介绍不会启动工作。',
  'tour.conflict': '介绍已在另一个标签页更新。请从已保存的步骤继续。',
  'tour.saveFailed': '无法保存进度，请重试。',
  'tour.wakeFailed': '尚未确认唤醒。请重试以检查同一请求。',
  'tour.loadFailed': '无法检查 Runtime 状态，请重试。',
  'tour.loading': '正在准备欢迎介绍…',
  'tour.sleeping': '您的智能参谋已准备好与您见面。',
  'tour.accepted': '唤醒请求已保存，正在等待 Runtime 开始。',
  'tour.blocked': 'Runtime 需要您的帮助以完成唤醒，请在本房间继续。',
  'tour.exploring': 'Runtime 正在了解您的公司，可在此查看进展。',
  'tour.unfinished': '唤醒尚未完成，请在此与 Runtime 继续。',
  'tour.label': '认识 Runtime',
  'tour.walkthrough': 'Runtime 入门介绍',
  'tour.alt': 'Runtime，您的复古电脑智能参谋',
  'tour.step': '第 {current} 步，共 5 步',
  'tour.back': '上一步',
  'tour.later': '稍后',
  'tour.next': '下一步',
  'tour.finish': '完成介绍',
  'tour.wake': '唤醒我',
  'tour.checking': '正在检查…',
  'tour.view': '查看介绍',
  'tour.continue': '继续介绍',
  'tour.check': '检查进展',
  'tour.resume': '继续唤醒',
  'tour.bringAlive': '唤醒 Runtime。',
  'tour.awakening': 'Runtime 正在唤醒。',
  'tour.refreshFailed': '无法刷新 Runtime 状态。',
  'tour.retry': '重试',
}
