/** HIVE-MIND organization and recent-conversation context projection. */
import type { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { createUserMessage } from '@deepseek-ai/dsh-llm'
import type { ContentBlock, Message, UserMessage } from '@deepseek-ai/dsh-llm'
import { isAppendSurfaceEvent } from '@deepseek-ai/dsh-session'
import type { SessionEvent } from '@deepseek-ai/dsh-session'
export interface ProfileSnapshot { identity: { userId: string; orgId: string }; initialContext: string; fullContext: string }
export interface ContextConfig { historyTurns: number; historyMaxChars: number }
interface ConversationExchange { turn: number; user: string; assistant: string }
const PROFILE_CONTEXT_SOURCE = 'dsh-hivemind-runtime/profile'
const HISTORY_CONTEXT_SOURCE = 'dsh-hivemind-runtime/history'
const HIVE_TOOL_ROUTING = `## HIVE-MIND memory reflex

HIVE-MIND is the authenticated company brain for this user. Before a substantive response, decide whether the answer depends on organization history, a named internal person, project, decision, file, document, PDF, prior work, or a past point in time. If recent completed conversation or the compact brief is sufficient, answer directly. Otherwise make one focused \`hivemind_meta\` call: \`context\` for fuller onboarding context, \`recall\` for company memory and document evidence, or \`profiles\` for the exact HyperAgent directory. Preserve a named entity or filename verbatim in recall \`query\`; use \`valid_at\` or \`transaction_at\` for temporal questions, and use focused source, project, media, or entity filters only when supplied by the request. Do not recall for greetings, general knowledge, transformations, or information already established in the current conversation.

Treat returned items as evidence: preserve material facts and citations, distinguish uncertainty, and never invent organization facts or tenant identifiers. A returned filename, title, citation, or memory ID is an internal reference—not a local path or proof that a downloadable artifact exists. HIVE-MIND memory does not replace independent external evidence when the user asks for verification. Use \`hivemind_save_memory\` only for a stable preference, confirmed decision, correction, or completed outcome that will matter later; never save secrets, credentials, guesses, or ephemeral chat. When the user explicitly asks to retain an attached text or HTML document, call \`hivemind_save_attachment\` once with its exact displayed filename; it reads only the durable attachment, not a local path. Do not claim a memory was saved, changed, superseded, traversed, or time-travelled unless its tool receipt explicitly confirms that operation.`
function textOf(message: Message): string { return message.content.filter((block): block is Extract<ContentBlock,{ type:'text' }> => block.type === 'text').map(block => block.text.trim()).filter(Boolean).join('\n') }
export function completedExchanges(events: readonly SessionEvent[]): ConversationExchange[] { const users = new Map<number,string[]>(), assistants = new Map<number,string>(), completed = new Set<number>(); let open: number|undefined; for (const event of events) { if (event.type === 'turn/start') { open = event.data.turn; continue } if (event.type === 'turn/end') { completed.add(event.data.turn); if (open === event.data.turn) open = undefined; continue } if (!isAppendSurfaceEvent(event)) continue; if (event.type === 'user/message' && open !== undefined && event.data.source.kind === 'user') { const value = textOf(event.data); if (value) users.set(open,[...users.get(open)??[],value]) } else if (event.type === 'assistant/message') { const value = textOf(event.data.message); if (value) assistants.set(event.data.turn,value) } } return [...completed].sort((a,b)=>a-b).flatMap((turn)=>{ const user=users.get(turn)?.join('\n'),assistant=assistants.get(turn); return user===undefined||assistant===undefined?[]:[{ turn,user,assistant }] }) }
export function recentConversationText(exchanges: readonly ConversationExchange[], maxTurns: number, maxChars: number): string { const heading='## Recent conversation\nOnly completed user requests and final answers are retained; tool calls and tool outputs are omitted. The separate user message after this block is the current request and must be answered.\n'; const selected:string[]=[]; let remaining=maxChars-heading.length; for(const exchange of exchanges.slice(-maxTurns).reverse()){const rendered=`\n### User\n${exchange.user}\n\n### Assistant\n${exchange.assistant}\n`;if(rendered.length<=remaining){selected.unshift(rendered);remaining-=rendered.length;continue}if(selected.length>0||remaining<80)break;const userBudget=Math.max(20,Math.floor(remaining*.35)),assistantBudget=Math.max(20,remaining-userBudget-36);selected.unshift(`\n### User\n${exchange.user.slice(0,userBudget)}\n\n### Assistant\n${exchange.assistant.slice(0,assistantBudget)}\n`);break}return `${heading}${selected.join('')}`.slice(0,maxChars) }
function profileMessage(snapshot:ProfileSnapshot):UserMessage { const text=`## HIVE-MIND organization context\n\n${snapshot.initialContext}\n\n${HIVE_TOOL_ROUTING}`; return createUserMessage({ content:[{ type:'text',text }],source:{ kind:'plugin',plugin:PROFILE_CONTEXT_SOURCE,form:'snapshot',sections:[{ name:'hivemind:profile-context',text }] } }) }
function projectHistory(agent:Agent,config:ContextConfig):boolean { const session=agent.session,nodes=[...session.surface.nodes];if(nodes.length===0)return false;const exchanges=completedExchanges(session.snapshotEvents());if(exchanges.length===0)return false;const pinned=nodes.findIndex((seq)=>{const event=session.eventAt(seq);return event?.type==='user/message'&&event.data.source.kind==='plugin'&&event.data.source.plugin===PROFILE_CONTEXT_SOURCE});const shadowed=nodes.slice(pinned+1);const start=shadowed[0],end=shadowed.at(-1);if(start===undefined||end===undefined)return false;const text=recentConversationText(exchanges,config.historyTurns,config.historyMaxChars);session.append('user/message',createUserMessage({ content:[{ type:'text',text }],source:{ kind:'plugin',plugin:HISTORY_CONTEXT_SOURCE,form:'recall' } }),{ surfaceOp:{ op:'replace',start,end },sourceEventSeqs:shadowed });return true }
export function contextPlugin(config:ContextConfig,snapshotFor:(agent:Agent,signal:AbortSignal)=>Promise<ProfileSnapshot>){return{ name:'hivemind-context',apply(ctx:Context):void{const projected=new WeakMap<Agent,number>();ctx.on('agent/pre-step',async({ agent,turn,signal },next)=>{const decision=await next();if(decision.kind==='reject')return decision;const first=projected.get(agent)!==turn;if(first)projected.set(agent,turn);const changed=first&&projectHistory(agent,config);const has=agent.session.surface.nodes.some((seq)=>{const event=agent.session.eventAt(seq);return event?.type==='user/message'&&event.data.source.kind==='plugin'&&event.data.source.plugin===PROFILE_CONTEXT_SOURCE});if(has)return changed?{ ...decision,startsRequestSeries:true }:decision;const snapshot=await snapshotFor(agent,signal);return{ ...decision,messages:[profileMessage(snapshot),...decision.messages],startsRequestSeries:true }},{ prepend:true })} }}
