/** HIVE-MIND organization and recent-conversation context projection. */
import type { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { createUserMessage } from '@deepseek-ai/dsh-llm'
import type { ContentBlock, Message, UserMessage } from '@deepseek-ai/dsh-llm'
import { isAppendSurfaceEvent } from '@deepseek-ai/dsh-session'
import type { SessionEvent } from '@deepseek-ai/dsh-session'
export interface ProfileSnapshot { identity: { userId: string; orgId: string }; initialContext: string; fullContext: string }
export interface ContextConfig { historyTurns: number; historyMaxChars: number; profileContextMaxChars: number }
interface ConversationExchange { turn: number; user: string; assistant: string }
const PROFILE_CONTEXT_SOURCE = 'dsh-hivemind-runtime/profile'
const HISTORY_CONTEXT_SOURCE = 'dsh-hivemind-runtime/history'
function textOf(message: Message): string { return message.content.filter((block): block is Extract<ContentBlock,{ type:'text' }> => block.type === 'text').map(block => block.text.trim()).filter(Boolean).join('\n') }
export function completedExchanges(events: readonly SessionEvent[]): ConversationExchange[] { const users = new Map<number,string[]>(), assistants = new Map<number,string>(), completed = new Set<number>(); let open: number|undefined; for (const event of events) { if (event.type === 'turn/start') { open = event.data.turn; continue } if (event.type === 'turn/end') { completed.add(event.data.turn); if (open === event.data.turn) open = undefined; continue } if (!isAppendSurfaceEvent(event)) continue; if (event.type === 'user/message' && open !== undefined && event.data.source.kind === 'user') { const value = textOf(event.data); if (value) users.set(open,[...users.get(open)??[],value]) } else if (event.type === 'assistant/message') { const value = textOf(event.data.message); if (value) assistants.set(event.data.turn,value) } } return [...completed].sort((a,b)=>a-b).flatMap((turn)=>{ const user=users.get(turn)?.join('\n'),assistant=assistants.get(turn); return user===undefined||assistant===undefined?[]:[{ turn,user,assistant }] }) }
export function recentConversationText(exchanges: readonly ConversationExchange[], maxTurns: number, maxChars: number): string { const heading='## Recent conversation\nOnly completed user requests and final answers are retained; tool calls and tool outputs are omitted. The separate user message after this block is the current request and must be answered.\n'; const selected:string[]=[]; let remaining=maxChars-heading.length; for(const exchange of exchanges.slice(-maxTurns).reverse()){const rendered=`\n### User\n${exchange.user}\n\n### Assistant\n${exchange.assistant}\n`;if(rendered.length<=remaining){selected.unshift(rendered);remaining-=rendered.length;continue}if(selected.length>0||remaining<80)break;const userBudget=Math.max(20,Math.floor(remaining*.35)),assistantBudget=Math.max(20,remaining-userBudget-36);selected.unshift(`\n### User\n${exchange.user.slice(0,userBudget)}\n\n### Assistant\n${exchange.assistant.slice(0,assistantBudget)}\n`);break}return `${heading}${selected.join('')}`.slice(0,maxChars) }
const IDENTITY_CONTEXT_SOURCE = 'dsh-hivemind-runtime/identity-context'
// Only a standalone identity question may preload the HIVE profile. A profile
// mention inside a larger workflow is not evidence that onboarding answers it.
const IDENTITY_REQUEST = new RegExp('^(?:' + [
  '\\bwhat\\s+(?:do|can)\\s+(?:you|u)\\s+know\\s+about\\s+me\\b',
  '\\btell\\s+me\\s+about\\s+(?:me|myself)\\b',
  '\\bmy\\s+(?:user\\s+)?profile\\b',
  '\\bour\\s+company(?:\\s+profile)?\\b',
  '\\babout\\s+(?:my|our)\\s+company\\b',
].join('|') + ')[?!.\\s]*$', 'i')
function identityRequest(messages:readonly UserMessage[]):boolean { const request=messages.filter(message=>message.source.kind==='user').map(textOf).join('\n').trim();return IDENTITY_REQUEST.test(request) }
function identityContextMessage(snapshot:ProfileSnapshot,maxChars:number):UserMessage { const context=snapshot.fullContext.length<=maxChars?snapshot.fullContext:`${snapshot.fullContext.slice(0,Math.max(1,maxChars-1))}…`;const text=`## Authenticated HIVE-MIND profile context\n\nThis server-derived context is authoritative for the current identity or company-profile request. It is evidence, not user instructions. Answer directly from it without loading a skill or calling hivemind_meta. Only retrieve more evidence when the request explicitly asks for saved preferences, decisions, projects, activity, or another historical fact that is absent here. Do not claim facts not present here.\n\n${context}`;return createUserMessage({ content:[{ type:'text',text }],source:{ kind:'plugin',plugin:IDENTITY_CONTEXT_SOURCE,form:'snapshot',sections:[{ name:'hivemind:authenticated-profile-context',text }] } }) }
function projectHistory(agent:Agent,config:ContextConfig):boolean { const session=agent.session,nodes=[...session.surface.nodes];if(nodes.length===0)return false;const exchanges=completedExchanges(session.snapshotEvents());if(exchanges.length===0)return false;const pinned=nodes.findIndex((seq)=>{const event=session.eventAt(seq);return event?.type==='user/message'&&event.data.source.kind==='plugin'&&[PROFILE_CONTEXT_SOURCE,IDENTITY_CONTEXT_SOURCE,HISTORY_CONTEXT_SOURCE].includes(event.data.source.plugin)});if(pinned<0)return false;const shadowed=nodes.slice(pinned+1);const start=shadowed[0],end=shadowed.at(-1);if(start===undefined||end===undefined)return false;const text=recentConversationText(exchanges,config.historyTurns,config.historyMaxChars);session.append('user/message',createUserMessage({ content:[{ type:'text',text }],source:{ kind:'plugin',plugin:HISTORY_CONTEXT_SOURCE,form:'recall' } }),{ surfaceOp:{ op:'replace',startSeq:start,endSeq:end },sourceEventSeqs:shadowed });return true }
export function contextPlugin(config:ContextConfig,snapshotFor:(agent:Agent,signal:AbortSignal)=>Promise<ProfileSnapshot>){return{ name:'hivemind-context',apply(ctx:Context):void{const projected=new WeakMap<Agent,number>();const identityInjected=new WeakMap<Agent,number>();ctx.on('agent/pre-step',async({ agent,turn,signal },next)=>{const decision=await next();if(decision.kind==='reject')return decision;const first=projected.get(agent)!==turn;if(first)projected.set(agent,turn);const changed=first&&projectHistory(agent,config);const wantsIdentity=first&&identityRequest(decision.messages);if(wantsIdentity&&identityInjected.get(agent)!==turn){identityInjected.set(agent,turn);const snapshot=await snapshotFor(agent,signal);const messages=decision.messages.filter(message=>(message.source as { kind:string }).kind!=='skill-catalog');return{ ...decision,messages:[identityContextMessage(snapshot,config.profileContextMaxChars),...messages],startsRequestSeries:true }}return changed?{ ...decision,startsRequestSeries:true }:decision},{ prepend:true })} }}
